language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test --cov contentful/ --cov-report term-missing test/
after_success:
  - coveralls